#------------------------------------------------------------------
#
# Values for the Custom NTFY-Helm-Chart
#
#------------------------------------------------------------------

# =================================================================
# Pod specifications
# =================================================================
#
# -- Number of Pods
# @section -- Pod specifications
replicaCount: 1
#
# -- The strategy used to replace old Pods by new ones
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
# @section -- Pod specifications
strategy:
  type: Recreate
#
# -- Pod Security Context
# @section -- Pod specifications
podSecurityContext:
  runAsUser: 10000
  runAsGroup: 10000
  fsGroup: 10000
  runAsNonRoot: true
#
# -- Additional Pod-annotations
# @section -- Pod specifications
podAnnotations: {}
#
# -- Additional Pod-Labels
# @section -- Pod specifications
podLabels: {}
#
# -- Additional Volumes
# @section -- Pod specifications
additionalVolumes: {}
#
# -- Kubernetes only schedules the Pod onto nodes that have each of the labels you specify
# @section -- Pod specifications
nodeSelector: {}
#
# -- Affinity expand the types of constraints you can define
# @section -- Pod specifications
affinity: {}
#
# -- Tolerations allow the scheduler to schedule pods with matching taints
# @section -- Pod specifications
tolerations: {}


# =================================================================
# Container specifications
# =================================================================
#
containers:
  ntfy:
    #
    # Image specifications of the NTFY-Container
    image:
      #
      # -- Container-Image-Repository
      # @section -- NTFY-Container specifications
      repository: "docker.io/binwiederhier/ntfy"
      #
      # -- Container-Image-Tag (by default `.Chart.AppVersion` will be used)
      # @section -- NTFY-Container specifications
      tag: "v2.21.0"
      #
      # -- Container-Image pull-policy
      # @section -- NTFY-Container specifications
      pullPolicy: IfNotPresent
    #
    # -- Container Security Context
    # @section -- NTFY-Container specifications
    securityContext:
      runAsUser: 10000
      runAsGroup: 10000
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      privileged: false
    #
    # -- Container Resources
    # @section -- NTFY-Container specifications
    resources: {}
    #resources:
    #  requests:
    #    memory: 200Mi
    #    cpu: 100m
    #  limits:
    #    memory: 500Mi
    #    cpu: 500m
    #
    service:
      # -- Service Type
      # @section -- NTFY-Container specifications
      type: ClusterIP
      #
      # @ignored
      ports:
        # @ignored
        - name: http
          #
          # reference containerPort
          # @ignored 
          containerPort: 5000
          #
          # -- Exposed Container-Port
          # @section -- NTFY-Container-Port
          port: 5000
          #
          # reference containerPort by name
          # @ignored
          targetPort: http
          #
          protocol: TCP
    #
    # -- Additional Volume-Mounts for Container
    # @section -- NTFY-Container specifications
    additionalVolumeMounts: {}
    #
    # -- Additional Environment-variables
    # @section -- NTFY-Container specifications
    additionalEnv: {}
    #
    # -- Additional Arguments
    # @section -- NTFY-Container specifications
    additionalArgs: {}
    #
    probes:
      #
      livenessProbe:
        #
        # -- Whether to enable the Liveness-Probe
        # @section -- NTFY-Container-Probes specifications
        enabled: true
        #
        # -- Initial Delay in Seconds
        # @section -- NTFY-Container-Probes specifications
        initialDelaySeconds: 30
        #
        # -- How often to perform the liveness checks
        # @section -- NTFY-Container-Probes specifications
        periodSeconds: 10
        #
        # -- Time to wait for a response from the database
        # @section -- NTFY-Container-Probes specifications
        timeoutSeconds: 5
        #
        # -- Number of consecutive failures before restarting the Pod
        # @section -- NTFY-Container-Probes specifications
        failureThreshold: 3
        #
        # -- Number of successful checks before considering the Pod healthy (again)
        # @section -- NTFY-Container-Probes specifications
        successThreshold: 1
      #
      readinessProbe:
        #
        # -- Whether to enable the Readiness-Probe
        # @section -- NTFY-Container-Probes specifications
        enabled: true
        #
        # -- How long to wait before starting the first readiness Probe after the container starts
        # @section -- NTFY-Container-Probes specifications
        initialDelaySeconds: 30
        #
        # -- How often to perform the readiness checks after the initial delay
        # @section -- NTFY-Container-Probes specifications
        periodSeconds: 5
        #
        # -- The maximum amount of time the probe will wait for a response from the application
        # @section -- NTFY-Container-Probes specifications
        timeoutSeconds: 2
        #
        # -- Number of consecutive failures before restarting the Pod
        # @section -- NTFY-Container-Probes specifications
        failureThreshold: 3
        #
        # -- Number of successful checks before considering the Pod healthy
        # @section -- NTFY-Container-Probes specifications
        successThreshold: 1


# =================================================================
# Authentication specifications
# =================================================================
#
authentication:
  authTokens:
    #
    # -- Name of an existing Secret for Authentication-Tokens.
    # A Secret will be created if not set.
    # @section -- NTFY-Authentication specifications
    existingSecretName: ""
    #
    # -- Secret-Key Name for Authentication-Tokens
    # @section -- NTFY-Authentication specifications
    secretKey: "auth-tokens"
  #
  authUsers:
    #
    # -- Name of an existing Secret for Authentication-Users.
    # A Secret will be created if not set.
    # @section -- NTFY-Authentication specifications
    existingSecretName: ""
    #
    # -- Secret-Key Name for Authentication-Users
    # @section -- NTFY-Authentication specifications
    secretKey: "auth-users"
  #
  authAccess:
    #
    # -- Name of an existing Secret for Authentication-Access.
    # A Secret will be created if not set.
    # @section -- NTFY-Authentication specifications
    existingSecretName: ""
    #
    # -- Secret-Key Name for Authentication-Access
    # @section -- NTFY-Authentication specifications
    secretKey: "auth-access"


# =================================================================
# Persistence specifications
# =================================================================
#
persistence:
  #
  # -- Whether to enable persistence for 'cache.db' and 'user.db' (enables PVC)
  # @section -- NTFY-Persistence specifications
  enabled: false
  #
  # -- SizeLimit for emptyDir (used when persistence/PVC is disabled)
  # @section -- NTFY-Persistence specifications
  emptyDirSizeLimit: "1Gi"
  #
  # -- Whether to create a new PVC
  # @section -- NTFY-Persistence specifications
  createNewPVC: true
  #
  # -- StorageClassName of the PVC
  # @section -- NTFY-Persistence specifications
  storageClassName: ""
  #
  # -- Name of the PVC
  # @section -- NTFY-Persistence specifications
  claimName: "ntfy-data-pvc"
  #
  # -- Access-Modes of the PVC
  # @section -- NTFY-Persistence specifications
  accessModes:
    - ReadWriteOnce
  #
  # -- storage-request for the PVC
  # @section -- NTFY-Persistence specifications
  storageRequest: "5Gi"


# =================================================================
# Config specifications
# =================================================================
#
configFiles:
  #
  # 'server.yaml'
  serverYAML:
    #
    # -- Whether to use your own 'server.yaml'-file
    # @section -- server.yaml Config-File
    useOwnConfigFileContent: false
    #
    # -- Provide own 'server.yaml' file-content
    # @section -- server.yaml Config-File
    ownConfigFileContent: ""
    #ownConfigFileContent: |
    #
    # Configure existing 'server.yaml'-file (will be ignored, if `useOwnConfigFileContent: true`)
    dynamicValues:
      #
      # -- Additional NTFY-YAML-Configuration that gets appended
      # to the YAML-config.
      # @section -- server.yaml Config-File
      additionalConfig: {}
      #
      # -- Whether NTFY is behind a Proxy
      # @section -- server.yaml Config-File
      behindProxy: false
      #
      # -- Forwarded Proxy-Header (e.g. "X-Forwarded-For")
      # @section -- server.yaml Config-File
      proxyForwardedHeader: ""
      #
      # -- A comma-separated list of IP addresses, hostnames or CIDRs that are removed from 
      # the forwarded header to determine the real IP address (e.g. "1.2.3.4, 5.6.7.8")
      # @section -- server.yaml Config-File
      proxyTrustedHosts: ""
      #
      # -- Public facing base URL of the service
      # @section -- server.yaml Config-File
      baseURL: ""
      #
      attachments:
        #
        # -- Whether to enable attachments.
        # `baseURL` and `attachments.cacheDir` has to be set!
        # @section -- server.yaml Config-File
        enabled: false
        #
        # -- The cache directory for attached files
        # @section -- server.yaml Config-File
        cacheDir: "/var/lib/ntfy"
        #
        # -- The limit of the on-disk attachment cache directory (total size)
        # @section -- server.yaml Config-File
        totalSizeLimit: "5G"
        #
        # -- The per-file attachment size limit (e.g. 300k, 2M, 100M)
        # @section -- server.yaml Config-File
        fileSizeLimit: "15M"
        #
        # -- The duration after which uploaded attachments will be deleted (e.g. 3h, 20h)
        # @section -- server.yaml Config-File
        expiryDuration: "3h"
      #
      rateLimits:
        #
        # -- Whether to enable subscriber-based rate limiting (mostly used for UnifiedPush)
        # @section -- server.yaml Config-File
        visitorSubscriberRateLimiting: false
        #
        # -- The max size of a message body
        # @section -- server.yaml Config-File
        messageSizeLimit: "4k"
        #
        # -- The max delay of a message when using the "Delay" header
        # @section -- server.yaml Config-File
        messageDelayLimit: "3d"
        #
        # -- Total number of topics before the server rejects new topics
        # @section -- server.yaml Config-File
        globalTopicLimit: 15000
        #
        # -- Number of subscriptions per visitor (IP address)
        # @section -- server.yaml Config-File
        visitorSubscriptionLimit: 30
        #
        # -- The initial bucket of requests each visitor has
        # @section -- server.yaml Config-File
        visitorRequestLimitBurst: 60
        #
        # -- The rate at which the bucket is refilled
        # @section -- server.yaml Config-File
        visitorRequestLimitReplenish: "5s"
        #
        # -- A comma-separated list of hostnames, IPs or CIDRs to be
        # exempt from request rate limiting. Hostnames are resolved at the time the server is started.
        # Example: "1.2.3.4,ntfy.example.com,8.7.6.0/24"
        # @section -- server.yaml Config-File
        visitorRequestLimitExemptHosts: ""
        #
        # -- Hard daily limit of messages per visitor and day. The limit is reset
        # every day at midnight UTC. If the limit is not set (or set to zero), the request
        # limit (see above) governs the upper limit.
        # @section -- server.yaml Config-File
        visitorMessageDailyLimit: 0
        #
        # -- The total storage limit used for attachments per visitor
        # @section -- server.yaml Config-File
        visitorAttachmentTotalSizeLimit: "100M"
        #
        # -- The total daily attachment download/upload traffic limit per visitor
        # @section -- server.yaml Config-File
        visitorAttachmentDailyBandwidthLimit: "500M"
      #
      # -- auth-file
      # @section -- server.yaml Config-File
      authFile: "/var/lib/ntfy/user.db"
      #
      # -- auth-default-access
      # @section -- server.yaml Config-File
      authDefaultAccess: "deny-all"
      #
      # -- auth-users (Secret is recommended instead)
      # @section -- server.yaml Config-File
      authUsers: []
      #authUsers:
      #  - "test-admin:$2a$10$1Y//CVdFIQRYNfIITwqZDeqnh0bFSM/Bhxjis5gKItcgU0UrSNWAa:admin"
      #  - "test-user:$2a$10$1Y//CVdFIQRYNfIITwqZDeqnh0bFSM/Bhxjis5gKItcgU0UrSNWAa:user"
      #
      # -- auth-access (Secret is recommended instead)
      # @section -- server.yaml Config-File
      authAccess: []
      #authAccess:
      #  - "test-user:TestTopic:rw"
      #
      # -- auth-tokens (Secret is recommended instead)
      # @section -- server.yaml Config-File
      authTokens: []
      #authTokens:
      #  - "test-user:tk_84t6qy4qxadevc37jbqty4q8xlpzl:Test-Token for Test-User"
      #
      # -- Messages are cached in a local SQLite database instead of only in-memory
      # @section -- server.yaml Config-File
      cacheFile: "/var/lib/ntfy/cache.db"
      #
      # -- Defines the duration for which messages will be buffered
      # before they are deleted
      # @section -- server.yaml Config-File
      cacheDuration: "72h"
      #
      # -- Allow enabling async batch writing of messages.
      # If set, messages will be queued and written to the database in batches of the given
      # size, or after the given timeout. This is only required for high volume servers.
      # @section -- server.yaml Config-File
      cacheBatchSize: 0
      #
      # -- Allow enabling async batch writing of messages.
      # If set, messages will be queued and written to the database in batches of the given
      # size, or after the given timeout. This is only required for high volume servers.
      # @section -- server.yaml Config-File
      cacheBatchTimeout: "0ms"
      #
      # -- Allows to run commands when the database is initialized
      # @section -- server.yaml Config-File
      cacheStartupQueries: ""
      #
      # -- Interval in which the manager prunes old messages, deletes topics
      # and prints the stats
      # @section -- server.yaml Config-File
      managerInterval: "1m"
      #
      # -- Topic names that are not allowed
      # @section -- server.yaml Config-File
      disallowedTopics: []
      #disallowedTopics:
      #  - Test
      #  - Not-Allowed
      #  - NotAllowed
      #  - Invalid
      # 
      # -- Defines the root path of the web app, or disables the web app entirely
      # @section -- server.yaml Config-File
      webRoot: /
      #
      # -- Whether to allow users to sign up via the web app, or API.
      # `enableLogin` needs to be set when enabled.
      # @section -- server.yaml Config-File
      enableSignup: false
      #
      # -- Whether to redirect users to the login page if they are not logged in (disallows web app access without login).
      # `enableLogin` needs to be set when enabled.
      # @section -- server.yaml Config-File
      requireLogin: false
      #
      # -- Whether to allow users to log in via the web app, or API
      # @section -- server.yaml Config-File
      enableLogin: false
      #
      # -- Whether to allow users to reserve topics (if their tier allows it)
      # @section -- server.yaml Config-File
      enableReservations: false
      #
      # -- Whether to enable Prometheus-style metrics via a `/metrics` endpoint 
      # or on a dedicated listen IP/port
      # @section -- server.yaml Config-File
      enableMetrics: false
      #
      # -- Exposes the metrics endpoint via a dedicated [IP]:port
      # @section -- server.yaml Config-File
      #metricsListenHttp: ":9090"
      #
      # -- Defines the default log level
      # @section -- server.yaml Config-File
      logLevel: "info"
      #
      # -- Log-level-overrides (for debugging, only use temporarily)
      # @section -- server.yaml Config-File
      logLevelOverrides: []
      #logLevelOverrides:
      #  - "tag=manager -> trace"
      #  - "visitor_ip=1.2.3.4 -> debug"
      #  - "time_taken_ms -> debug"
      #
      # -- Defines the output format, can be "text" (default) or "json"
      # @section -- server.yaml Config-File
      logFormat: "json"
      #
      # -- Filename to write logs to. If this is not set, ntfy logs to stderr.
      # @section -- server.yaml Config-File
      logFile: ""


# =================================================================
# IngressRoute specifications
# =================================================================
#
ingressRoute:
  #
  # -- Whether to enable the IngressRoute for NTFY
  # @section -- IngressRoute specifications
  enabled: false
  #
  # -- Listening for Incoming Connections/Requests
  # https://doc.traefik.io/traefik/reference/install-configuration/entrypoints/
  # @section -- IngressRoute specifications
  entryPoints:
    - websecure
  #
  # -- Name of the Certificate Resolver to use to generate automatic TLS certificates.
  # https://doc.traefik.io/traefik/reference/install-configuration/tls/certificate-resolvers/overview/
  # @section -- IngressRoute specifications
  certResolver: ""
  #
  # -- Hostname
  # @section -- IngressRoute specifications
  host: ""
