#------------------------------------------------------------------------
#
# Helm-Values for the ntfy-Helm chart
#
#------------------------------------------------------------------------

# =======================================================================
# Pod specifications
# =======================================================================
#
# -- Number of Pods
# @section -- Pod specifications
replicaCount: 1
#
# -- The strategy used to replace old Pods by new ones
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
# @section -- Pod specifications
strategy:
  type: Recreate
#
# -- Pod Security Context
# @section -- Pod specifications
podSecurityContext:
  runAsUser: 10000
  runAsGroup: 10000
  fsGroup: 10000
  runAsNonRoot: true
#
# -- Additional Pod-annotations
# @section -- Pod specifications
podAnnotations: {}
#
# -- Additional Pod-Labels
# @section -- Pod specifications
podLabels: {}
#
# -- Kubernetes only schedules the Pod onto nodes that have each of the labels you specify
# @section -- Pod specifications
nodeSelector: {}
#
# -- Affinity expand the types of constraints you can define
# @section -- Pod specifications
affinity: {}
#
# -- Tolerations allow the scheduler to schedule pods with matching taints
# @section -- Pod specifications
tolerations: {}
#
# -- Additional Volumes
# @section -- Pod specifications
extraVolumes: {}


# =======================================================================
# Containers specifications
# =======================================================================
#
# -- List of additional init-Containers
# @section -- Additional init-Container specifications
extraInitContainers: []
#
# -- List of sidecar-Containers
# @section -- Additional sidecar-Containers
extraContainers: []
#
ntfyContainer:
  image:
    #
    # -- Container-Image registry
    # @section -- NTFY-Container specifications
    registry: "docker.io"
    #
    # -- Container-Image repository
    # @section -- NTFY-Container specifications
    repository: "binwiederhier/ntfy"
    #
    # -- Container-Image-Tag (overrides `.Chart.AppVersion`)
    # @section -- NTFY-Container specifications
    tag: ""
    #
    # -- Container-Image pull-policy
    # @section -- NTFY-Container specifications
    pullPolicy: IfNotPresent
  #
  # -- Container Security Context
  # @section -- NTFY-Container specifications
  securityContext:
    runAsUser: 10000
    runAsGroup: 10000
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    privileged: false
  #
  # -- Container Resources
  # @section -- NTFY-Container specifications
  resources: {}
  #
  service:
    #
    # -- Name of the NTFY-Service resource
    # @section -- NTFY-Service specifications
    serviceName: ntfy-http
    #
    # -- Type of the NTFY-Service resource
    # @section -- NTFY-Service specifications
    type: ClusterIP
    ports:
      # @ignored
      - name: http
        #
        # container-Port
        # @ignored
        containerPort: 5000
        #
        # -- Exposed Service-Port
        # @section -- NTFY-Service specifications
        port: 5000
        # @ignored
        targetPort: http
        # @ignored
        protocol: TCP
  #
  # -- Additional VolumeMounts
  # @section -- NTFY-Container specifications
  extraVolumeMonts: []
  #
  # -- Additional environment-Variables
  # @section -- NTFY-Container specifications
  extraEnvs: []
  #
  # -- Additional Container-arguments
  # @section -- NTFY-Container specifications
  extraArgs: []
  #
  # -- Startup-Probe
  # @section -- NTFY-Container specifications
  startupProbe: {}
  #
  # -- Readiness-Probe
  # @section -- NTFY-Container specifications
  readinessProbe: {}
  #
  # -- Liveness-Probe
  # @section -- NTFY-Container specifications
  livenessProbe: {}


# =======================================================================
# Authentication specifications
# =======================================================================
authentication:
  authTokens:
    #
    # -- Whether to use an existing Secret or not
    # @section -- NTFY-Authentication specifications
    useExistingSecret: false
    #
    # -- Name of the Secret for Authentication-Tokens.
    # @section -- NTFY-Authentication specifications
    secretName: ""
    #
    # -- Secret-Key Name for Authentication-Tokens
    # @section -- NTFY-Authentication specifications
    secretKey: "auth-tokens"
    #
    # -- Default Secret-Value.
    # ignored when `authTokens.useExistingSecret: true`
    # @section -- NTFY-Authentication specifications
    defaultSecretValue: |-
      test-user:tk_84t6qy4qxadevc37jbqty4q8xlpzl:Test-Token for Test-User
  #
  authUsers:
    #
    # -- Whether to use an existing Secret or not
    # @section -- NTFY-Authentication specifications
    useExistingSecret: false
    #
    # -- Name of the Secret for Authentication-Users.
    # @section -- NTFY-Authentication specifications
    secretName: ""
    #
    # -- Secret-Key Name for Authentication-Users
    # @section -- NTFY-Authentication specifications
    secretKey: "auth-users"
    #
    # -- Default Secret-Value.
    # ignored when `authTokens.useExistingSecret: true`
    # @section -- NTFY-Authentication specifications
    defaultSecretValue: |-
      test-admin:$2a$10$1Y//CVdFIQRYNfIITwqZDeqnh0bFSM/Bhxjis5gKItcgU0UrSNWAa:admin,test-user:$2a$10$1Y//CVdFIQRYNfIITwqZDeqnh0bFSM/Bhxjis5gKItcgU0UrSNWAa:user
  #
  authAccess:
    #
    # -- Whether to use an existing Secret or not
    # @section -- NTFY-Authentication specifications
    useExistingSecret: false
    #
    # -- Name of the Secret for Authentication-Access.
    # @section -- NTFY-Authentication specifications
    secretName: ""
    #
    # -- Secret-Key Name for Authentication-Access
    # @section -- NTFY-Authentication specifications
    secretKey: "auth-access"
    #
    # -- Default Secret-Value.
    # ignored when `authTokens.useExistingSecret: true`
    # @section -- NTFY-Authentication specifications
    defaultSecretValue: |-
      test-user:TestTopic:rw


# =================================================================
# Persistence specifications
# =================================================================
persistence:
  #
  # -- Whether to enable persistence for 'cache.db' and 'user.db' (enables PVC)
  # Otherwise an emptyDir gets used the the databases.
  # @section -- NTFY-Persistence specifications
  enabled: true
  #
  # -- EmptyDir-Object that is being used when persistence is disabled.
  # @section -- NTFY-Persistence specifications
  emptyDir:
    sizeLimit: 1Gi
  #
  persistentVolumeClaim:
    #
    # -- Whether to use an existing PersistentVolumeClaim or not.
    # @section -- NTFY-Persistence specifications
    useExistingPVC: true
    #
    # -- StorageClassName of the PVC.
    # ignored when `useExistingPVC: false`
    # @section -- NTFY-Persistence specifications
    storageClassName: ""
    #
    # -- Name of the PVC
    # @section -- NTFY-Persistence specifications
    claimName: ""
    #
    # -- Access-Modes of the PVC.
    # ignored when `useExistingPVC: false`
    # @section -- NTFY-Persistence specifications
    accessModes: ["ReadWriteOnce"]
    #
    # -- `resources.storage.request` for the PVC.
    # ignored when `useExistingPVC: false`
    # @section -- NTFY-Persistence specifications
    storageRequest: "5Gi"
    #
    # -- additional specs for the PVC.
    # ignored when `useExistingPVC: false`
    # @section -- NTFY-Persistence specifications
    extraSpecs: {}


# =================================================================
# Config-files specifications
# =================================================================
serverConfig:
  #
  # -- Whether to use an existing ConfigMap instead of creating one.
  # @section -- Server-Config specifications
  useExistingConfigMap: false
  #
  # -- Name of the ConfigMap
  # @section -- Server-Config specifications
  configMapName: ""
  #
  # -- Key to the ConfigMap-item
  # @section -- Server-Config specifications
  configMapItemKey: "server.yaml"
  #
  # ignored when `useExistingConfigMap: true`
  dynamicValues:
    #
    # -- Append additional lines to the server-config-file
    # @section -- Server-Config specifications
    extraConfig: ""
    #
    # -- Whether NTFY is behind a Proxy
    # @section -- Server-Config specifications
    behindProxy: false
    #
    # -- Forwarded Proxy-Header (e.g. "X-Forwarded-For")
    # @section -- Server-Config specifications
    proxyForwardedHeader: ""
    #
    # -- A comma-separated list of IP addresses, hostnames or CIDRs that are removed from 
    # the forwarded header to determine the real IP address (e.g. "1.2.3.4, 5.6.7.8")
    # @section -- Server-Config specifications
    proxyTrustedHosts: ""
    #
    # -- Public facing base URL of the service
    # @section -- Server-Config specifications
    baseURL: ""
    #
    attachments:
      #
      # -- Whether to enable attachments.
      # `baseURL` and `attachments.cacheDir` has to be set!
      # @section -- Server-Config specifications
      enabled: false
      #
      # -- The cache directory for attached files
      # @section -- Server-Config specifications
      cacheDir: "/var/lib/ntfy"
      #
      # -- The limit of the on-disk attachment cache directory (total size)
      # @section -- Server-Config specifications
      totalSizeLimit: "5G"
      #
      # -- The per-file attachment size limit (e.g. 300k, 2M, 100M)
      # @section -- Server-Config specifications
      fileSizeLimit: "15M"
      #
      # -- The duration after which uploaded attachments will be deleted (e.g. 3h, 20h)
      # @section -- Server-Config specifications
      expiryDuration: "3h"
    #
    rateLimits:
      #
      # -- Whether to enable subscriber-based rate limiting (mostly used for UnifiedPush)
      # @section -- Server-Config specifications
      visitorSubscriberRateLimiting: false
      #
      # -- The max size of a message body
      # @section -- Server-Config specifications
      messageSizeLimit: "4k"
      #
      # -- The max delay of a message when using the "Delay" header
      # @section -- Server-Config specifications
      messageDelayLimit: "3d"
      #
      # -- Total number of topics before the server rejects new topics
      # @section -- Server-Config specifications
      globalTopicLimit: 15000
      #
      # -- Number of subscriptions per visitor (IP address)
      # @section -- Server-Config specifications
      visitorSubscriptionLimit: 30
      #
      # -- The initial bucket of requests each visitor has
      # @section -- Server-Config specifications
      visitorRequestLimitBurst: 60
      #
      # -- The rate at which the bucket is refilled
      # @section -- Server-Config specifications
      visitorRequestLimitReplenish: "5s"
      #
      # -- A comma-separated list of hostnames, IPs or CIDRs to be
      # exempt from request rate limiting. Hostnames are resolved at the time the server is started.
      # Example: "1.2.3.4,ntfy.example.com,8.7.6.0/24"
      # @section -- Server-Config specifications
      visitorRequestLimitExemptHosts: ""
      #
      # -- Hard daily limit of messages per visitor and day. The limit is reset
      # every day at midnight UTC. If the limit is not set (or set to zero), the request
      # limit (see above) governs the upper limit.
      # @section -- Server-Config specifications
      visitorMessageDailyLimit: 0
      #
      # -- The total storage limit used for attachments per visitor
      # @section -- Server-Config specifications
      visitorAttachmentTotalSizeLimit: "100M"
      #
      # -- The total daily attachment download/upload traffic limit per visitor
      # @section -- Server-Config specifications
      visitorAttachmentDailyBandwidthLimit: "500M"
    #
    # -- auth-file
    # @section -- Server-Config specifications
    authFile: "/var/lib/ntfy/user.db"
    #
    # -- auth-default-access
    # @section -- Server-Config specifications
    authDefaultAccess: "deny-all"
    #
    # -- auth-users (Secret is recommended instead)
    # @section -- Server-Config specifications
    authUsers: []
    #authUsers:
    #  - "test-admin:$2a$10$1Y//CVdFIQRYNfIITwqZDeqnh0bFSM/Bhxjis5gKItcgU0UrSNWAa:admin"
    #  - "test-user:$2a$10$1Y//CVdFIQRYNfIITwqZDeqnh0bFSM/Bhxjis5gKItcgU0UrSNWAa:user"
    #
    # -- auth-access (Secret is recommended instead)
    # @section -- Server-Config specifications
    authAccess: []
    #authAccess:
    #  - "test-user:TestTopic:rw"
    #
    # -- auth-tokens (Secret is recommended instead)
    # @section -- Server-Config specifications
    authTokens: []
    #authTokens:
    #  - "test-user:tk_84t6qy4qxadevc37jbqty4q8xlpzl:Test-Token for Test-User"
    #
    # -- Messages are cached in a local SQLite database instead of only in-memory
    # @section -- Server-Config specifications
    cacheFile: "/var/lib/ntfy/cache.db"
    #
    # -- Defines the duration for which messages will be buffered
    # before they are deleted
    # @section -- Server-Config specifications
    cacheDuration: "72h"
    #
    # -- Allow enabling async batch writing of messages.
    # If set, messages will be queued and written to the database in batches of the given
    # size, or after the given timeout. This is only required for high volume servers.
    # @section -- Server-Config specifications
    cacheBatchSize: 0
    #
    # -- Allow enabling async batch writing of messages.
    # If set, messages will be queued and written to the database in batches of the given
    # size, or after the given timeout. This is only required for high volume servers.
    # @section -- Server-Config specifications
    cacheBatchTimeout: "0ms"
    #
    # -- Allows to run commands when the database is initialized
    # @section -- Server-Config specifications
    cacheStartupQueries: ""
    #
    # -- Interval in which the manager prunes old messages, deletes topics
    # and prints the stats
    # @section -- Server-Config specifications
    managerInterval: "1m"
    #
    # -- Topic names that are not allowed
    # @section -- Server-Config specifications
    disallowedTopics: []
    #disallowedTopics:
    #  - Test
    #  - Not-Allowed
    #  - NotAllowed
    #  - Invalid
    # 
    # -- Defines the root path of the web app, or disables the web app entirely
    # @section -- Server-Config specifications
    webRoot: "/"
    #
    # -- Whether to allow users to sign up via the web app, or API.
    # `enableLogin` needs to be set when enabled.
    # @section -- Server-Config specifications
    enableSignup: false
    #
    # -- Whether to redirect users to the login page if they are not logged in (disallows web app access without login).
    # `enableLogin` needs to be set when enabled.
    # @section -- Server-Config specifications
    requireLogin: false
    #
    # -- Whether to allow users to log in via the web app, or API
    # @section -- Server-Config specifications
    enableLogin: false
    #
    # -- Whether to allow users to reserve topics (if their tier allows it)
    # @section -- Server-Config specifications
    enableReservations: false
    #
    # -- Whether to enable Prometheus-style metrics via a `/metrics` endpoint 
    # or on a dedicated listen IP/port
    # @section -- Server-Config specifications
    enableMetrics: false
    #
    # -- Exposes the metrics endpoint via a dedicated [IP]:port
    # @section -- Server-Config specifications
    #metricsListenHttp: ":9090"
    #
    # -- Defines the default log level
    # @section -- Server-Config specifications
    logLevel: "info"
    #
    # -- Log-level-overrides (for debugging, only use temporarily)
    # @section -- Server-Config specifications
    logLevelOverrides: []
    #logLevelOverrides:
    #  - "tag=manager -> trace"
    #  - "visitor_ip=1.2.3.4 -> debug"
    #  - "time_taken_ms -> debug"
    #
    # -- Defines the output format, can be "text" (default) or "json"
    # @section -- Server-Config specifications
    logFormat: "json"
    #
    # -- Filename to write logs to. If this is not set, ntfy logs to stderr.
    # @section -- Server-Config specifications
    logFile: ""
