repos:
  - repo: local
    hooks:
      - id: check-if-chart-version-bumped
        name: check-if-chart-version-bumped
        entry: bash -c 'scripts/pre-commit.sh'
        language: system
        pass_filenames: false

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs
        args:
          #
          # Make the tool search for charts only under the `example-charts` directory
          - --chart-search-root=charts
          #
          # For charts with dependencies, include the dependency values in the chart values documentation
          - --document-dependency-values
