repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs
        args:
          #
          # Make the tool search for charts only under the `example-charts` directory
          - --chart-search-root=charts
          #
          # For charts with dependencies, include the dependency values in the chart values documentation
          - --document-dependency-values
