#------------------------------------------------------------------
#
# Values for the Custom Radicale Helm-Chart
#
#------------------------------------------------------------------

# =================================================================
# Pod specifications
# =================================================================
#
# -- Number of Pods
# @section -- Pod specifications
replicaCount: 1
#
# -- The strategy used to replace old Pods by new ones
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
# @section -- Pod specifications
strategy:
  type: Recreate
#
# -- Pod Security Context
# @section -- Pod specifications
podSecurityContext:
  runAsUser: 2999
  runAsGroup: 2999
  fsGroup: 2999
  runAsNonRoot: true
#
# -- Additional Pod-annotations
# @section -- Pod specifications
podAnnotations: {}
#
# -- Additional Pod-Labels
# @section -- Pod specifications
podLabels: {}
#
# -- Additional Volumes
# @section -- Pod specifications
additionalVolumes: {}
#
# -- Kubernetes only schedules the Pod onto nodes that have each of the labels you specify
# @section -- Pod specifications
nodeSelector: {}
#
# -- Affinity expand the types of constraints you can define
# @section -- Pod specifications
affinity: {}
#
# -- Tolerations allow the scheduler to schedule pods with matching taints
# @section -- Pod specifications
tolerations: {}


# =================================================================
# Container specifications
# =================================================================
#
containers:
  radicale:
    #
    # Image specifications of the NTFY-Container
    image:
      #
      # -- Container-Image-Repository
      # @section -- Radicale-Container specifications
      repository: "tomsquest/docker-radicale"
      #
      # -- Container-Image-Tag (by default `.Chart.AppVersion` will be used)
      # @section -- Radicale-Container specifications
      tag: "3.6.1.0"
      #
      # -- Container-Image pull-policy
      # @section -- Radicale-Container specifications
      pullPolicy: IfNotPresent
    #
    # -- Container Security Context
    # @section -- Radicale-Container specifications
    securityContext:
      runAsUser: 2999
      runAsGroup: 2999
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      privileged: false
    #
    # -- Container Resources
    # @section -- Radicale-Container specifications
    resources: {}
    #resources:
    #  requests:
    #    memory: 200Mi
    #    cpu: 100m
    #  limits:
    #    memory: 500Mi
    #    cpu: 500m
    #
    service:
      # -- Service Type
      # @section -- Radicale-Container specifications
      type: ClusterIP
      #
      # @ignored
      ports:
        # @ignored
        - name: http
          #
          # reference containerPort
          # @ignored 
          containerPort: 5232
          #
          # -- Exposed Container-Port
          # @section -- NTFY-Container-Port
          port: 5232
          #
          # reference containerPort by name
          # @ignored
          targetPort: http
          #
          protocol: TCP
    #
    # -- Additional Volume-Mounts for Container
    # @section -- Radicale-Container specifications
    additionalVolumeMounts: {}
    #
    # -- Additional Environment-variables
    # @section -- Radicale-Container specifications
    additionalEnv: {}
    #
    # -- Additional Arguments
    # @section -- Radicale-Container specifications
    additionalArgs: {}
    #
    probes:
      #
      livenessProbe:
        #
        # -- Whether to enable the Liveness-Probe
        # @section -- Radicale-Container-Probes specifications
        enabled: true
        #
        # -- Initial Delay in Seconds
        # @section -- Radicale-Container-Probes specifications
        initialDelaySeconds: 30
        #
        # -- How often to perform the liveness checks
        # @section -- Radicale-Container-Probes specifications
        periodSeconds: 10
        #
        # -- Time to wait for a response from the database
        # @section -- Radicale-Container-Probes specifications
        timeoutSeconds: 5
        #
        # -- Number of consecutive failures before restarting the Pod
        # @section -- Radicale-Container-Probes specifications
        failureThreshold: 3
        #
        # -- Number of successful checks before considering the Pod healthy (again)
        # @section -- Radicale-Container-Probes specifications
        successThreshold: 1
      #
      readinessProbe:
        #
        # -- Whether to enable the Readiness-Probe
        # @section -- Radicale-Container-Probes specifications
        enabled: true
        #
        # -- How long to wait before starting the first readiness Probe after the container starts
        # @section -- Radicale-Container-Probes specifications
        initialDelaySeconds: 30
        #
        # -- How often to perform the readiness checks after the initial delay
        # @section -- Radicale-Container-Probes specifications
        periodSeconds: 5
        #
        # -- The maximum amount of time the probe will wait for a response from the application
        # @section -- Radicale-Container-Probes specifications
        timeoutSeconds: 2
        #
        # -- Number of consecutive failures before restarting the Pod
        # @section -- Radicale-Container-Probes specifications
        failureThreshold: 3
        #
        # -- Number of successful checks before considering the Pod healthy
        # @section -- Radicale-Container-Probes specifications
        successThreshold: 1


# =================================================================
# Authentication specifications
# =================================================================
#
authentication:
  #
  # -- Name of an existing Secret for Users.
  # A Secret will be created if not set.
  # @section -- Radicale-Authentication specifications
  existingSecretName: ""
  #
  # -- Secret-Key Name for Users
  # @section -- Radicale-Authentication specifications
  secretKey: "users"


# =================================================================
# Persistence specifications
# =================================================================
#
persistence:
  #
  # -- Whether to enable persistence for collections-data (enables PVC).
  # Otherwise local ephemeral storage is being used (emptyDir).
  # @section -- Radicale-Persistence specifications
  enabled: true
  #
  # -- SizeLimit for emptyDir (used when persistence is disabled)
  # @section -- Radicale-Persistence specifications
  emptyDirSizeLimit: "1Gi"
  #
  # -- Whether to create a new PVC
  # @section -- Radicale-Persistence specifications
  createNewPVC: true
  #
  # -- StorageClassName of the PVC
  # @section -- Radicale-Persistence specifications
  storageClassName: ""
  #
  # -- Name of the PVC
  # @section -- Radicale-Persistence specifications
  claimName: ""
  #
  # -- Access-Modes of the PVC
  # @section -- Radicale-Persistence specifications
  accessModes:
    - ReadWriteOnce
  #
  # -- storage-request for the PVC
  # @section -- Radicale-Persistence specifications
  storageRequest: "5Gi"


# =================================================================
# Config specifications
# =================================================================
#
configFiles:
  #
  # 'config'
  config:
    #
    # -- Whether to use your own 'config'-file
    # @section -- config Config-File
    useOwnConfigFileContent: false
    #
    # -- Provide own 'config' file-content
    # @section -- config Config-File
    ownConfigFileContent: ""
    #ownConfigFileContent: |
    #
    # Configure existing 'config'-file (will be ignored, if `useOwnConfigFileContent: true`)
    dynamicValues:
      #
      # -- Additional Radicale-Configuration that gets appended
      # @section -- config Config-File
      additionalConfig: {}


# =================================================================
# IngressRoute specifications
# =================================================================
#
ingressRoute:
  #
  # -- Whether to enable the IngressRoute for NTFY
  # @section -- IngressRoute specifications
  enabled: false
  #
  # -- Listening for Incoming Connections/Requests
  # https://doc.traefik.io/traefik/reference/install-configuration/entrypoints/
  # @section -- IngressRoute specifications
  entryPoints:
    - websecure
  #
  # -- Name of the Certificate Resolver to use to generate automatic TLS certificates.
  # https://doc.traefik.io/traefik/reference/install-configuration/tls/certificate-resolvers/overview/
  # @section -- IngressRoute specifications
  certResolver: ""
  #
  # -- Hostname
  # @section -- IngressRoute specifications
  host: ""