{{ include "ntfy.validateValues" . }}
{{- $serverConfig := .Values.serverConfig -}}
{{- if (include "ntfy.createConfigMap" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ntfy.configMapName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "ntfy.labels" . | nindent 4 }}
data:
  {{ $serverConfig.configMapItemKey }}: |-
    {{- tpl ($.Files.Get "config/server.yaml") . | nindent 4 }}
{{- end }}