{{ include "ntfy.validateValues" . }}
{{- $ingressRoute := .Values.ingressRoute -}}
{{- if $ingressRoute.enabled }}
{{- $ntfyContainer := .Values.ntfyContainer -}}
{{- $ntfyContainerServicePorts := $ntfyContainer.service.ports -}}
{{- $middlewares := .Values.middlewares -}}
{{- $namespace := .Release.Namespace | quote -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "ntfy.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- (include "ntfy.labels" .) | nindent 4 }}
spec:
  entryPoints: {{- $ingressRoute.entryPoints | toYaml | nindent 4 }}
  routes:
  - match: {{ $ingressRoute.routeMatch }}
    kind: Rule
    services:
    - name: {{ include "ntfy.fullname" . }}
      port: {{ index $ntfyContainerServicePorts 0 "port" }}
      scheme: http
    {{- if $middlewares }}
    middlewares:
    {{- range $middlewares }}
    - name: {{ .name }}
      namespace: {{ $namespace }}
    {{- end }}
    {{- end }}
  tls:
    certResolver: {{ $ingressRoute.certResolver }}
{{- end }}
