{{ include "ntfy.validateValues" . }}
{{- $persistence := .Values.persistence -}}
{{- $pvc := $persistence.persistentVolumeClaim -}}
{{- if (include "ntfy.createPersistentVolumeClaim" .) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ntfy.persistentVolumeClaimName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "ntfy.labels" . | nindent 4 }}
spec:
  storageClassName: {{ $pvc.storageClassName }}
  accessModes: {{ $pvc.accessModes | toYaml | nindent 2 }}
  resources:
    requests:
      storage: {{ $pvc.storageRequest }}
  {{- if $pvc.extraSpecs }}
  {{- $pvc.extraSpecs | toYaml | nindent 2 }}
  {{- end }}
{{- end }}