{{- $auth := .Values.authentication -}}
{{- if or (not $auth.authTokens.existingSecretName) (not $auth.authUsers.existingSecretName) (not $auth.authAccess.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ntfy.authTokensSecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ntfy.labels" . | nindent 4 }}
stringData:
  {{- if not $auth.authTokens.existingSecretName }}
  auth-tokens: "test-user:tk_84t6qy4qxadevc37jbqty4q8xlpzl:Test-Token for Test-User"
  {{- end }}
  {{- if not $auth.authUsers.existingSecretName }}
  auth-users: "test-admin:$2a$10$1Y//CVdFIQRYNfIITwqZDeqnh0bFSM/Bhxjis5gKItcgU0UrSNWAa:admin,test-user:$2a$10$1Y//CVdFIQRYNfIITwqZDeqnh0bFSM/Bhxjis5gKItcgU0UrSNWAa:user"
  {{- end }}
  {{- if not $auth.authAccess.existingSecretName }}
  auth-access: "test-user:TestTopic:rw"
  {{- end }}
{{- end }}