{{ include "ntfy.validateValues" . }}
{{- $authentication := .Values.authentication -}}
{{- $authTokens := $authentication.authTokens -}}
{{- $authUsers := $authentication.authUsers -}}
{{- $authAccess := $authentication.authAccess -}}
{{- if (include "ntfy.createSecret" .) }}
{{- $namespace := .Release.Namespace | quote -}}
{{- $labels := (include "ntfy.labels" .) -}}
{{- $secrets := list -}}
{{- if not $authTokens.useExistingSecret }}
{{- $secrets = append $secrets $authTokens -}}
{{- end }}
{{- if not $authUsers.useExistingSecret }}
{{- $secrets = append $secrets $authUsers -}}
{{- end }}
{{- if not $authAccess.useExistingSecret }}
{{- $secrets = append $secrets $authAccess -}}
{{- end }}
{{- $secretNames := (include "ntfy.secretNames" .) | fromJsonArray -}}
{{- range $index, $secret := $secrets }}
{{- if not $secret.useExistingSecret }}
{{- if gt $index 0 }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index $secretNames $index }}
  namespace: {{ $namespace }}
  labels: {{- $labels | nindent 4 }}
stringData:
  {{ $secret.secretKey }}: {{ $secret.defaultSecretValue | toYaml | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}