{{ include "librefrontier.validateValues" . }}
{{- $librefrontierContainer := .Values.containers.librefrontier -}}
{{- $librefrontierConfig := .Values.librefrontierConfig -}}
{{- $librefrontierContainerLivenessProbe := $librefrontierContainer.probes.livenessProbe -}}
{{- $librefrontierContainerReadinessProbe := $librefrontierContainer.probes.readinessProbe -}}
{{- $httpAPIIngressRoute := .Values.httpAPIIngressRoute -}}
{{- $webUIIngressRoute := .Values.webUIIngressRoute -}}
{{- $initContainers := .Values.initContainers -}}
{{- $services := $librefrontierContainer.services -}}
{{- $httpAPIService := $services.httpAPI -}}
{{- $webUIService := $services.webUI -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "librefrontier.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "librefrontier.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy: {{ toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "librefrontier.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/service: {{ include (print $.Template.BasePath "/service.yaml") . | sha256sum }}
        {{- if or $webUIIngressRoute.enabled $httpAPIIngressRoute.enabled }}
        checksum/ingress-route: {{ include (print $.Template.BasePath "/ingress-route.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "librefrontier.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with $librefrontierContainer.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "librefrontier.containerImage" . }}
          imagePullPolicy: {{ $librefrontierContainer.image.pullPolicy }}
          ports:
            - name: http-api
              containerPort: {{ $httpAPIService.containerPort }}
            {{- if $webUIService.enabled }}
            - name: web-ui
              containerPort: {{ $webUIService.containerPort }}
            {{- end }}
          env:
            - name: GIN_MODE
              value: {{ $librefrontierConfig.ginMode }}
            - name: LF_API_BASE_URL
              value: {{ $librefrontierConfig.LFAPIBaseURL }}
            - name: LF_DB_CONN_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ include "librefrontier.databaseConnectionString.secretName" . }}
                  key: "database-connection-string"
            {{- with $librefrontierContainer.additionalEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with $librefrontierContainer.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with $librefrontierContainerLivenessProbe }}
          {{- if .enabled }}
          livenessProbe:
            tcpSocket:
              port: http-api
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            failureThreshold: {{ .failureThreshold }}
            successThreshold: {{ .successThreshold }}
          {{- end }}
          {{- end }}
          {{- with $librefrontierContainerReadinessProbe }}
          {{- if .enabled }}
          readinessProbe:
            tcpSocket:
              port: http-api
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            failureThreshold: {{ .failureThreshold }}
            successThreshold: {{ .successThreshold }}
          {{- end }}
          {{- end }}
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
