{{ include "librefrontier.validateValues" . }}
{{- $httpAPIIngressRoute := .Values.httpAPIIngressRoute -}}
{{- $webUIIngressRoute := .Values.webUIIngressRoute -}}
{{- $librefrontierContainer := .Values.containers.librefrontier -}}
{{- $services := $librefrontierContainer.services -}}
{{- $httpAPIService := $services.httpAPI -}}
{{- $webUIService := $services.webUI -}}
{{- if and $webUIService.enabled $webUIIngressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "librefrontier.fullname" . }}-webui
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "librefrontier.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml $webUIIngressRoute.entryPoints | nindent 4 }}
  routes:
    - match: {{ $webUIIngressRoute.routeMatch | quote }}
      kind: Rule
      services:
        - name: {{ include "librefrontier.serviceName.webUI" . }}
          port: {{ $webUIService.port }}
          scheme: http
  tls:
    certResolver: {{ $webUIIngressRoute.certResolver }}
{{- end }}
{{- if $httpAPIIngressRoute.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "librefrontier.fullname" . }}-http-api
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "librefrontier.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml $httpAPIIngressRoute.entryPoints | nindent 4 }}
  routes:
    - match: {{ $httpAPIIngressRoute.routeMatch | quote }}
      kind: Rule
      services:
        - name: {{ include "librefrontier.serviceName.httpAPI" . }}
          port: {{ $httpAPIService.port }}
          scheme: http
{{- end -}}
