{{ include "librefrontier.validateValues" . }}
{{- $ingressRoute := .Values.ingressRoute -}}
{{- if $ingressRoute.enabled }}
{{- $librefrontierContainer := .Values.containers.librefrontier -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "librefrontier.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  entryPoints:
    {{- toYaml $ingressRoute.entryPoints | nindent 4 }}
  routes:
    - match: Host(`{{ $ingressRoute.APIHost }}`)
      kind: Rule
      services:
        - name: {{ include "librefrontier.fullname" . }}
          port: {{ index $librefrontierContainer.service.ports 0 "port" }}
          scheme: http
    - match: Host(`{{ $ingressRoute.webUIHost }}`)
      kind: Rule
      services:
        - name: {{ include "librefrontier.fullname" . }}
          port: {{ index $librefrontierContainer.service.ports 1 "port" }}
          scheme: http
  tls:
    certResolver: {{ $ingressRoute.certResolver }}
{{- end }}
