{{- $config := .Values.librefrontierConfig -}}
{{- if not $config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "librefrontier.databaseConnectionString.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
stringData:
  database-connection-string: "{{ $config.databaseConnectionString.stringData }}"
{{- end -}}
