{{ include "librefrontier.validateValues" . }}
{{- $librefrontierContainer := .Values.containers.librefrontier -}}
{{- $services := $librefrontierContainer.services -}}
{{- $httpAPIService := $services.httpAPI -}}
{{- $webUIService := $services.webUI -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "librefrontier.serviceName.httpAPI" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "librefrontier.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "librefrontier.selectorLabels" . | nindent 6 }}
  type: {{ $httpAPIService.type }}
  ports:
    - name: http-api
      port: {{ $httpAPIService.port }}
      targetPort: http-api
      protocol: TCP
      nodePort: {{ $httpAPIService.nodePort }}
---
{{- if $webUIService.enabled }}
apiVersion: v1
kind: Service
metadata:
   name: {{ include "librefrontier.serviceName.webUI" . }}
   namespace: {{ .Release.Namespace | quote }}
   labels:
     {{- include "librefrontier.selectorLabels" . | nindent 4 }}
spec:
   selector: {{- include "librefrontier.selectorLabels" . | nindent 6 }}
   type: {{ $webUIService.type }}
   ports:
     - name: web-ui
       port: {{ $webUIService.port }}
       targetPort: web-ui
       protocol: TCP
       nodePort: {{ $webUIService.nodePort }}
{{- end -}}
