{{ include "radicale.validateValues" . }}
{{- $config := .Values.configFile -}}
{{- if (include "radicale.createConfigMap" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "radicale.configMapName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "radicale.labels" . | nindent 4 }}
data:
  {{ $config.configMapKey }}: |-
    {{- tpl (.Files.Get "config/config.conf") . | nindent 4 }}
{{- end }}
