{{ include "radicale.validateValues" . }}
{{- $radicaleContainer := .Values.radicaleContainer -}}
{{- $radicaleContainerLivenessProbe := $radicaleContainer.livenessProbe -}}
{{- $radicaleContainerReadinessProbe := $radicaleContainer.readinessProbe -}}
{{- $persistence := .Values.persistence -}}
{{- $authentication := .Values.authentication -}}
{{- $ingressRoute := .Values.ingressRoute -}}
{{- $configFile := .Values.configFile -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radicale.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "radicale.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy: {{ toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels: {{- include "radicale.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if (include "radicale.createConfigMap" .) }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if (include "radicale.createPVC" .) }}
        checksum/pvc: {{ include (print $.Template.BasePath "/pvc.yaml") . | sha256sum }}
        {{- end }}
        checksum/service: {{ include (print $.Template.BasePath "/service.yaml") . | sha256sum }}
        {{- if $ingressRoute.enabled }}
        checksum/ingress-route: {{ include (print $.Template.BasePath "/ingress-route.yaml") . | sha256sum }}
        {{- end }}
        {{- if (include "radicale.createSecret" .) }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "radicale.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{- .Values.imagePullSecrets | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext }}
      securityContext: {{- .Values.podSecurityContext | toYaml | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ include "radicale.containerImage" . }}
        imagePullPolicy: {{ $radicaleContainer.image.pullPolicy }}
        ports:
        {{- range $radicaleContainer.service.ports }}
        - name: {{ .name }}
          containerPort: {{ .containerPort }}
        {{- end }}
        {{- if $radicaleContainer.environmentVariables }}
        env: {{- $radicaleContainer.environmentVariables | toYaml | nindent 8 }}
        {{- end }}
        {{- if $radicaleContainer.securityContext }}
        securityContext: {{- $radicaleContainer.securityContext | toYaml | nindent 10 }}
        {{- end }}
        {{- with $radicaleContainerLivenessProbe }}
        {{- if .enabled }}
        livenessProbe:
          tcpSocket:
            port: {{ index $radicaleContainer.service.ports 0 "name" }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
          failureThreshold: {{ .failureThreshold }}
          successThreshold: {{ .successThreshold }}
        {{- end }}
        {{- end }}
        {{- with $radicaleContainerReadinessProbe }}
        {{- if .enabled }}
        readinessProbe:
          tcpSocket:
            port: {{ index $radicaleContainer.service.ports 0 "name" }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
          failureThreshold: {{ .failureThreshold }}
          successThreshold: {{ .successThreshold }}
        {{- end }}
        {{- end }}
        {{- with $radicaleContainer.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        - name: data
          mountPath: /data
        {{- if $radicaleContainer.extraVolumeMounts }}
        {{- $radicaleContainer.extraVolumeMounts | toYaml | nindent 8 }}
        {{- end }}
      {{- if .Values.extraContainers }}
      {{- .Values.extraContainers | toYaml | nindent 6 }}
      {{- end }}
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      volumes:
      - name: config
        projected:
          sources:
          - secret:
              name: {{ include "radicale.secretName" . }}
          - configMap:
              name: {{ include "radicale.configMapName" . }}
              items:
              - key: {{ $configFile.configMapKey }}
                path: config
      {{- if $persistence.enabled }}
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "radicale.pvcName" . }}
      {{- else }}
      - name: data
        emptyDir:
          sizeLimit: {{ $persistence.emptyDirSizeLimit }}
      {{- end }}
      {{- if .Values.extraVolumes }}
      {{- .Values.extraVolumes | toYaml | nindent 6 }}
      {{- end }}
