{{ include "radicale.validateValues" . }}
{{- $ingressRoute := .Values.ingressRoute -}}
{{- if $ingressRoute.enabled }}
{{- $middlewares := .Values.middlewares -}}
{{- if $middlewares }}
{{- $namespace := (.Release.Namespace | quote) -}}
{{- range $middlewares }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .name | quote }}
  namespace: {{ $namespace }}
spec:
  {{- toYaml .spec | nindent 2 }}
---
{{- end }}
{{- end }}
{{- end }}