{{ include "radicale.validateValues" . }}
{{- $persistence := .Values.persistence -}}
{{- if and $persistence.enabled $persistence.createNewPVC }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "radicale.pvc" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "radicale.labels" . | nindent 4 }}
spec:
  storageClassName: {{ $persistence.storageClassName }}
  accessModes: {{ toYaml $persistence.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ $persistence.storageRequest }}
{{- end }}