{{ include "radicale.validateValues" . }}
{{- $persistence := .Values.persistence -}}
{{- if (include "radicale.createPVC" .) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "radicale.pvcName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "radicale.labels" . | nindent 4 }}
spec:
  storageClassName: {{ $persistence.storageClassName }}
  accessModes: {{ toYaml $persistence.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ $persistence.storageRequest }}
{{- end }}
