{{ include "radicale.validateValues" . }}
{{- $auth := .Values.authentication -}}
{{- if not $auth.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "radicale.secret" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "radicale.labels" . | nindent 4 }}
stringData:
  #
  # test:lol1234
  users: |-
    test:$2y$05$HcQyLhN2cCClMVqulAZ4Xe42BX5WM5HTk3BgrgO/U8wfuOMT7t00a
{{- end }}