{{ include "radicale.validateValues" . }}
{{- $auth := .Values.authentication -}}
{{- if not $auth.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "radicale.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "radicale.labels" . | nindent 4 }}
stringData:
  users: ""
{{- end }}