{{ include "radicale.validateValues" . }}
{{- $radicaleContainerServce := .Values.containers.radicale.service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "radicale.service" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "radicale.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "radicale.selectorLabels" . | nindent 6 }}
  type: {{ $radicaleContainerServce.type }}
  ports:
    {{- range $radicaleContainerServce.ports }}
    - protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      name: {{ .name }}
    {{- end }}
