{{ include "radicale.validateValues" . }}
{{- $radicaleContainer := .Values.radicaleContainer -}}
{{- $service := $radicaleContainer.service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "radicale.serviceName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "radicale.labels" . | nindent 4 }}
spec:
  selector: {{- include "radicale.selectorLabels" . | nindent 4 }}
  type: {{ $service.type }}
  ports:
  {{- range $service.ports }}
  - protocol: {{ .protocol }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    name: {{ .name }}
  {{- end }}
